SELECT A.CATEGORY, SUM(B.SALES)
FROM BOOK A INNER JOIN BOOK_SALES B
                   ON A.BOOK_ID = B.BOOK_ID
WHERE TO_CHAR(B.SALES_DATE, 'yyyy-MM') = '2022-01'
GROUP BY A.CATEGORY
ORDER BY CATEGORY ASC